[package]
name = "day-1"
version = "0.1.0"
authors = ["Pete Wildsmith <pwildsmith@ebay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = {path = "../util"}
itertools = "0.9.0"
